name: UPM on npsjs.com
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Get release name
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          echo "Release Name: $RELEASE_NAME"
          RELEASE_NAME=$(echo "${RELEASE_NAME}" | cut -d '-' -f 1)
          echo "Release Name: $RELEASE_NAME"
          # Write into environment
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
      - name: NPM publish
        run: npm publish
        working-directory: Packages/com.prototyper.${{ env.RELEASE_NAME }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
