name: UPM on npsjs.com
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Get release name
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          echo "Release Name: $RELEASE_NAME"
          RELEASE_NAME=$(echo "${RELEASE_NAME}" | cut -d '-' -f 1)
          echo "Release Name: $RELEASE_NAME"
      - run: |
          # npm publish
        working-directory: Packages/com.prototyper.utility
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
